version: '3.8'
services:
  node_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=win_node_db
    ports:
      - '5432:5432'
    volumes: 
      - node_db_data:/var/lib/postgresql/data
  server:
    build: .
    ports: 
      - "3000:3000"
    volumes:
      - /home/workspace/node_modules
      - .:/home/workspace/
    environment:
      - PG_USER=postgres
      - PG_HOST=node_db
      - PG_DATABASE=win_node_db
      - PG_PASSWORD=12345678
      - PG_PORT=5432
    depends_on:
      - node_db
  testing-server:
    build: .
    volumes:
      - /home/workspace/node_modules
      - .:/home/workspace/
    environment:
      - PG_USER=postgres
      - PG_HOST=node_db
      - PG_DATABASE=win_node_db
      - PG_PASSWORD=12345678
      - PG_PORT=5432
    depends_on:
      - node_db
    command: npm run test
  pgadmin:
    image: dpage/pgadmin4
    environment: 
        - PGADMIN_DEFAULT_EMAIL=d@1.com
        - PGADMIN_DEFAULT_PASSWORD=1234
    ports: 
        - "5000:80"
volumes:
  node_db_data: {}      